### PR TITLE
DEB-99565, add diagnostic tool to nuget

### PR DESCRIPTION
**Pull request by wenpengxu**
@tmessina , @mjmessina-tt 

it creates 'bin' directory and saves the test tool and its required dlls in the directory.

Steps to test:

cd SDKs\dotnet
"\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\MSBuild" -m -t:Rebuild -p:Configuration=Release tt-net.sln /property:Platform=x64 /property:Configuration=Release
cd tt-net-sdk
..\build-sdk\nuget pack tt-net-api.csproj -properties Configuration=Release

then,
    copy the package file to your local nuget directory, and use visual studio to install the package from that directory.

### CODE REVIEW

**Comment by tmessina** [comment]
I read there is also a tools target. Do you know what the difference would be between the bin and tools targets are? I looked but didn't find any concrete answer about what goes where and I wonder if you did.

**Comment by wenpengxu** [comment]
tool/ is in solution
bin/ is for the package, after clients install ttnetapi, the dll file is under  lib/.  this creates bin/ at the same level.

**Comment by tmessina** [comment]
lg

**Comment by tmessina** [comment]
Thanks!

**Pull request merged**
